# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-01 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0002_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
